### PR TITLE
Misc. documentation fixes + automated tests

### PR DESCRIPTION
**Pull request by amoeba**
This PR makes a number of documentation fixes/changes and a starting set of automated tests.

I noticed that RStudio clobbered the line endings (are you on Windows?) when I saved files and the git diffs are less than useful. I hope you can still figure out what I changed but I'm happy to try fixing the diff (not sure how off-hand).

### CODE REVIEW

**Comment by arcaravaggi** [comment]
I'll post queries here as I run into them, rather than in the review thread. It might be a bit difficult to deal with changes to individual files as they've all been pushed together.

Why did you restore documentation and retain the export on `bsD` which is called by `boot_sd` and isn't user-facing, but removed the export on other non-user-facing functions, e.g. `grpDat_func`?

**Comment by amoeba** [comment]
Just to get R CMD CHECK to quiet down. Here's the relevant section from R CMD CHECK with the @export tag removed:

```
> ### Name: bsD
> ### Title: Required for remsD bootstrapping
> ### Aliases: bsD
> ### Keywords: bootstrap density, encounter model, population, random
> 
> ### ** Examples
> 
> nboots <- 1000
> tm <- 3600
> v <- 1.4
> grpDat <- split_dat(hDat)
> lapply(grpDat, function(x){
+   replicate(nboots, bsD(x, tm, v)) 
+ })
Error in FUN(X[[i]], ...) : could not find function "bsD"
Calls: lapply -> FUN -> replicate -> sapply -> lapply -> FUN
Execution halted
```

Adding @export back on removes the ERROR.

Given that it's probably obscenely hard to find what I changed due to the line ending changes, how about you accept the test commit and reject the other commit and I'll re-PR?

**Comment by arcaravaggi** [comment]
That error is exactly what I was getting if I removed @export from the other functions. But, if it's working...

If you wouldn't mind. I've cherry-picked the test commit and will close this pull request.

**Comment by amoeba** [comment]
Great. I'll re-PR the R CMD CHECK changes.

**Pull request closed without merging**
